const data = [
    {
        path: 'lyrics-finder',
        imgURL: require('../images/lyrics-finder.jpg'),
        logo: require('../images/ga-logo.png'),
        title: 'Lyrics Finder',
        projectId: 'Project 1',
        description: 'Lyrics Finder is a browser application that uses Genius API to fetch the result of the artist being searched. Based on the results the app does a second fetch of the artist and first song in the array and returns a YouTube video. There is an second API that searches for the lyrics based on the artist name and song title. Unfortunately, this API is no longer working. I will be working on a new update to find an alternative lyrics API.',
        gitHubURL: 'https://github.com/luisv7/project1',
        launchAppURL: 'https://iridescent-longma-c0b7c8.netlify.app/',
    },
    {
        path: 'tableres',
        imgURL: require('../images/tableres.jpg'),
        logo: require('../images/ga-logo.png'),
        title: 'TableRes Manager',
        projectId: 'Project 2',
        description: 'Do you run a restaurant? Are you having trouble managing your guest?TableRes Manager can help. Managing your guest was never this easy. TableRes has great features such as search by Name, filter by date, and filter by time.',
        gitHubURL: 'https://github.com/luisv7/TableRes-Manager',
        launchAppURL: 'https://tableres-manager.onrender.com',
    },
    {
        path: 'ecom-dash',
        imgURL: require('../images/ecom-dash.jpg'),
        logo: require('../images/ga-logo.png'),
        title: 'Ecom Dash',
        projectId: 'Project 3',
        description: 'With Ecom Dash you can build an e-commerce website in minutes. Simply add your product information, image URL, and you have a clean yet simple catalog/store. New updates coming soon to this project.',
        gitHubURL: 'https://github.com/luisv7/ecom-dash-frontend',
        launchAppURL: 'https://ecomdash-store.netlify.app',
    },
    {
        path: 'schoolpy',
        imgURL: require('../images/schoolpy.jpg'),
        logo: require('../images/ga-logo.png'),
        title: 'Schoolpy',
        projectId: 'Project 4',
        description: "SchoolPy is a learning management platform that allows students and teachers to be organized. Features such as creating assignments, adding courses you're currently enrolled in, and general class announcements.",
        gitHubURL: 'https://github.com/luisv7/schoolpy',
        launchAppURL: '#',
    },
    {
        path: 'falopeztrucking',
        imgURL: require('../images/falopeztrucking.jpg'),
        logo: require('../images/wordpress-logo.jpg'),
        title: 'FA Lopez Trucking',
        projectId: 'Project 5',
        description: 'FA Lopez Trucking offers efficient transportation solutions for all your cargo needs. They also provide other services such as dumpster rental, container rental and equipment rental.',
        gitHubURL: '#',
        launchAppURL: 'https://falopeztrucking.com',
    },
]

export default data;